# Generated by Django 3.2.9 on 2021-12-06 05:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_gamelog', '0003_followship'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.FloatField(default=0.0)),
                ('date', models.DateField(default=datetime.date.today)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gamelog.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
