# Generated by Django 3.2.9 on 2021-12-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gamelog', '0005_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='is_publisher',
            field=models.BooleanField(default=False),
        ),
    ]
