# Generated by Django 3.2.9 on 2021-12-06 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gamelog', '0006_publisher_is_publisher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publisher',
            options={'verbose_name': 'publisher', 'verbose_name_plural': 'publishers'},
        ),
    ]
