# Generated by Django 3.2.9 on 2021-12-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gamelog', '0007_alter_publisher_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('', ''), ('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
