# Generated by Django 3.2.9 on 2021-12-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gamelog', '0008_auto_20211206_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('', ''), ('Male', 'Male'), ('Female', 'Female')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
