# Generated by Django 3.2.9 on 2021-12-06 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('app_gamelog', '0009_auto_20211206_1739'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
