# Generated by Django 3.2.9 on 2021-12-06 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_gamelog', '0013_publishgame'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalFeeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('played', 'played'), ('purchased', 'purchased')], max_length=100)),
                ('value', models.FloatField(default=0.0)),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
