# Generated by Django 3.2.9 on 2021-12-07 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gamelog', '0017_auto_20211207_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
