# Generated by Django 3.2.9 on 2021-12-07 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_gamelog', '0018_alter_feed_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='target_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feed',
            name='action',
            field=models.CharField(choices=[('played', 'played'), ('purchased', 'purchased'), ('published', 'published'), ('followed', 'followed')], max_length=100),
        ),
        migrations.AlterField(
            model_name='feed',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_gamelog.game'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
